--- 
commit:
  emojis: false
  scope: true
  lower_case: true
  types:
    - name: feat
      description: A new feature
      emoji: 'âœ¨'
    - name: fix 
      description: A bug fix
    - name: style
      emoji: 'ğŸ›'
      description: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
    - name: test 
      description: Adding missing tests or correcting existing tests
      emoji: 'ğŸš¨'
    - name: refactor
      description:  A code change that neither fixes a bug nor adds a feature
      emoji: 'ğŸ“¦'
    - name: build
      description: "Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)"
      emoji: 'ğŸ› '
    - name: ci
      description: "Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)"
      emoji: 'âš™ï¸'
    - name: chore 
      description: Other changes that don't modify src or test files
      emoji: 'â™»ï¸'
    - name: revert
      description: Reverts a previous commit
      emoji: 'ğŸ—‘'
    - name: docs
      description: Documentation only changes
      emoji: 'ğŸ“š'
  message_length: 100
  co_authoring_file: co-authors.yml
  