--- 
commit:
  scope: true
  lower_case: true
  min_message_length: 5
  max_message_length: 100
  scope_length: 15
  co_authoring_file: co-authors.yml
  emojis: false
  types:
    - name: feat
      description: A new feature
      emoji: '‚ú®'
    - name: fix 
      description: A bug fix
    - name: style
      emoji: 'üêõ'
      description: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
    - name: test 
      description: Adding missing tests or correcting existing tests
      emoji: 'üö®'
    - name: refactor
      description:  A code change that neither fixes a bug nor adds a feature
      emoji: 'üì¶'
    - name: build
      description: "Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)"
      emoji: 'üõ†'
    - name: ci
      description: "Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)"
      emoji: '‚öôÔ∏è'
    - name: chore 
      description: Other changes that don't modify src or test files
      emoji: '‚ôªÔ∏è'
    - name: revert
      description: Reverts a previous commit
      emoji: 'üóë'
    - name: docs
      description: Documentation only changes
      emoji: 'üìö'
message:
    select_files: "Select files to commit:"
    staged_files: "Selected files to commit:"
    change_type: "Select change type:"
    scope: "What is the scope of this change? (enter to skip)"
    commit_message: "Enter a commit message: (max %d chars)"
    co_author_yes_no: "Would you like to add a co-author"
    co_author: "Who is your co-author?"
    co_author_name: "What is your co-author's name?"
    co_author_email: "What is your co-author's email address?"
exit:
    not_a_repo: Current directory is not in a repository - exiting script
    no_files_selected: No files selected for staging area - exiting script
    no_files_to_commit: No modified files, nothing to commit - exiting script
    commit_error: "Unexpected error while trying to perform: \n  %s"
